apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "myapp"
    meta.helm.sh/release-namespace: "default"
spec:
  capacity:
    storage: 1Gi  
  accessModes:
    - ReadWriteOnce  
  persistentVolumeReclaimPolicy: Retain  
  storageClassName: manual
  hostPath:
    path: "/mnt/data"

