ingress:
  host: a02d89b7b24714d5d988cfb712dadbbd-1833324318.us-east-1.elb.amazonaws.com
frontend:
  replicas: 2
  image:
    repository: 869935092862.dkr.ecr.us-east-1.amazonaws.com/frontend
    tag: latest
  service-type: ClusterIP  # Can be ClusterIP, NodePort, or LoadBalancer

backend:
  replicas: 2
  image:
    repository: 869935092862.dkr.ecr.us-east-1.amazonaws.com/backend
    tag: latest
  env:
    - name: FLASK_RUN_HOST
      value: "0.0.0.0"
  servicetype: ClusterIP  # Can be ClusterIP, NodePort, or LoadBalancer

mysql:
  servicetype: ClusterIP  # MySQL service type, usually ClusterIP for internal communication

