ingress:
  host: aa7fe1989b7284f8883c723c53771037-b02f2dd49f0811c4.elb.us-east-1.amazonaws.com
frontend:
  replicas: 2
  image:
    repository: 869935092862.dkr.ecr.us-east-1.amazonaws.com/frontend
    tag: latest
  service-type: ClusterIP  # Can be ClusterIP, NodePort, or LoadBalancer

backend:
  replicas: 2
  image:
    repository: 869935092862.dkr.ecr.us-east-1.amazonaws.com/backend
    tag: latest
  env:
    - name: FLASK_RUN_HOST
      value: "0.0.0.0"
  servicetype: ClusterIP  # Can be ClusterIP, NodePort, or LoadBalancer

mysql:
  servicetype: ClusterIP  # MySQL service type, usually ClusterIP for internal communication

